name: "lint"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: [self-hosted, linux, ARM64] 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use venv
        run: |
          if [ ! -d ".venv" ]; then
            uv venv
          fi
          source .venv/bin/activate

      - name: Lint Python
        run: |
          uvx ruff check .
    
      - name: Lint JS
        run: |
          uvx npm run lint --prefix frontend/feed-this-much-client
